[pytest]
norecursedirs = _disabled
addopts = 
    --verbose 
    --tb=short 
    --strict-markers 
    --ignore=notes 
    --ignore=docs 
    --capture=sys 
    --doctest-modules
testpaths = 
  tests
  src/uti
doctest_plus = enabled
markers =
  done:     @pytest.mark.done
  todo:     @pytest.mark.todo
  now:      @pytest.mark.now
  needs_review: Needs further attention in future.
filterwarnings =
  ignore::DeprecationWarning:dateutil.*
  ignore::DeprecationWarning:jupyter_client.*
  ignore::UserWarning
